apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test
spec:
  schedulerName: seal-scheduler
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80

